name: Build iOsApp IPA 🚀

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repozitáře 📥
        uses: actions/checkout@v4

      - name: Instalace XcodeGen 🛠️
        run: brew install xcodegen

      - name: Generování Xcode Projektu (iOsApp.xcodeproj) 🏗️
        run: xcodegen generate

      - name: Archivace iOS aplikace (.app) 📱
        run: |
          xcodebuild archive \
            -project iOsApp.xcodeproj \
            -scheme iOsApp \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath build/iOsApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            COMPILER_SIGN_INPUTS=NO

      - name: Vytvoření iOsApp.ipa balíčku 📦
        run: |
          mkdir -p Payload
          cp -r build/iOsApp.xcarchive/Products/Applications/iOsApp.app Payload/
          zip -r iOsApp.ipa Payload

      - name: Nahrání iOsApp.ipa do GitHub Artifacts 📤
        uses: actions/upload-artifact@v4
        with:
          name: iOsApp-IPA
          path: iOsApp.ipa
